[package]
name = "jpm_compiler"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
jpm_es_spec = { path = "../es-spec" }
jpm_package = { path = "../package" }
futures = "0.3.28"
miette = { workspace = true }
oxipng = "8.0.0"
swc = "0.264.15"
swc_common = "0.31.17"
starbase_styles = { workspace = true }
starbase_utils = { workspace = true }
thiserror = { workspace = true }

