[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
miette = "5.10.0"
starbase_sandbox = { version = "0.1.6" }
starbase_styles = "0.1.12"
starbase_utils = { version = "0.2.14", default-features = false }
thiserror = "1.0.44"
tokio = { version = "1.29.1", features = ["full", "tracing"] }
tracing = "0.1.37"
