[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
miette = "5.9.0"
starbase_sandbox = { version = "0.1.5" }
starbase_styles = "0.1.11"
starbase_utils = { version = "0.2.13", default-features = false }
thiserror = "1.0.40"
tokio = { version = "1.29.1", features = ["full", "tracing"] }
tracing = "0.1.37"
