[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
clap = { version = "4.3.21", default-features = false, features = ["std"] }
miette = "5.10.0"
once_cell = "1.18.0"
relative-path = { version = "1.8.0", features = ["serde"] }
schematic = { version = "0.11.2", default-features = false, features = [
	"toml",
	"type_relative_path",
	"type_url",
	"valid_url",
] }
semver = "1.0.18"
serde = "1.0.183"
starbase = "0.2.0"
starbase_sandbox = { version = "0.1.8" }
starbase_styles = "0.1.12"
starbase_utils = { version = "0.2.17", default-features = false, features = [
	"glob",
] }
thiserror = "1.0.44"
tokio = { version = "1.29.1", features = ["full", "tracing"] }
tracing = "0.1.37"
url = { version = "2.4.0", features = ["serde"] }
