[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
clap = { version = "4.3.19", default-features = false, features = ["std"] }
miette = "5.10.0"
schematic = { version = "0.11.0", default-features = false, features = [
	"toml",
] }
semver = "1.0.18"
serde = "1.0.177"
starbase = "0.2.0"
starbase_sandbox = { version = "0.1.8" }
starbase_styles = "0.1.12"
starbase_utils = { version = "0.2.14", default-features = false, features = [
	"glob",
] }
thiserror = "1.0.44"
tokio = { version = "1.29.1", features = ["full", "tracing"] }
tracing = "0.1.37"
