[package]
name = "espresso_tsconfig"
version = "0.0.1"
edition = "2021"
license = "MIT"
publish = false

[dependencies]
relative-path = { workspace = true }
schematic = { workspace = true }
serde = { workspace = true }
