[package]
name = "jpm_cli"
version = "0.1.0"
edition = "2021"
license = "MIT"

[[bin]]
name = "jpm"
path = "src/main.rs"

[dependencies]
jpm_common = { path = "../common" }
jpm_compiler = { path = "../compiler" }
jpm_package = { path = "../package" }
clap = { workspace = true, features = ["derive", "env", "wrap_help"] }
miette = { workspace = true }
mimalloc = { version = "0.1.37", default-features = false }
starbase = { workspace = true }
tokio = { workspace = true }
