[package]
name = "jpm_package"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
miette = { workspace = true }
starbase_styles = { workspace = true }
starbase_utils = { workspace = true }
thiserror = { workspace = true }
